name: Lint and Test Charts

on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      # continue with all the other jobs even if one fails
      fail-fast: false
      matrix:
        # each item in this list is a job with an isolated test VM
        test_cases:
          # test the plain helm chart with nothing changed
          - name: 'Default - no custom values'

          # test the helm chart with postgresql subchart enabled
          - name: PostgreSQL Enabled
            helm_args: '--helm-extra-set-args "--set=postgresql.enabled=true --set=postgresql.global.postgresql.auth.password=testing123456 --set=internalDatabase.enabled=false --set=externalDatabase.enabled=True --set=externalDatabase.type=postgresql --set=externalDatabase.password=testing12345"'

          # test the helm chart with nginx container enabled
          - name: Nginx Enabled
            helm_args: '--helm-extra-set-args "--set=image.flavor=fpm --set=nginx.enabled=true"'

          # test the helm chart with horizontal pod autoscaling enabled
          - name: Horizontal Pod Autoscaling Enabled
            helm_args: '--helm-extra-set-args "--set=hpa.enabled=true --set=hpa.minPods=2 --set=hpa.maxPods=3 --set=hpa.targetCPUUtilizationPercentage=75"'

          # test the helm chart with s3 as the primary storage
          - name: S3 Enabled as Primary Storage
            # we need to skip the clean up so we can test adding a file
            helm_args: |
                --namespace nextcloud --skip-clean-up --helm-extra-set-args "--set=fullnameOverride=nextcloud --set=nextcloud.objectStore.s3.enabled=true --set=nextcloud.objectStore.s3.accessKey=nextcloud --set=nextcloud.objectStore.s3.secretKey=rootpass123 --set=nextcloud.objectStore.s3.host=minio.nextcloud.svc.cluster.local --set=nextcloud.objectStore.s3.port=9000 --set=nextcloud.objectStore.s3.ssl=false --set=nextcloud.objectStore.s3.bucket=nextcloud --set=nextcloud.objectStore.s3.usePathStyle=true --set=image.flavor=fpm --set=nginx.enabled=true --set=nextcloud.host=nextcloud --set=nextcloud.trustedDomains[0]='*'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install MinIO for testing S3 as Primary Storage
        if: matrix.test_cases.name == 'S3 Enabled as Primary Storage'
        # installs minio community helm chart here:
        # https://github.com/minio/minio/tree/master/helm/minio
        run: |
          helm repo add minio https://charts.min.io/ && \
          helm install minio \
             --namespace nextcloud \
             --create-namespace \
             --wait \
             --wait-for-jobs \
             --timeout 2m0s \
             --values .github/tests/minio_test_values.yaml \
             minio/minio

      - name: Run chart-testing (install ${{ matrix.test_cases.name }})
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} ${{ matrix.test_cases.helm_args }}

      - name: Try adding a file to Nextcloud
        if: matrix.test_cases.name == 'S3 Enabled as Primary Storage'
        # applies a kubernetes job that uploads a file and then checks log of finished pod
        run: |
            kubectl config set-context --current --namespace=nextcloud && \
            kubectl apply -f ./.github/tests/test_upload_job.yaml --wait=true && \
            sleep 2 && \
            kubectl wait --for=condition=Complete --timeout=2m job/create-nextcloud-file && \
            echo "Here's the logs from the job:" && \
            kubectl logs --tail=-1 -f -l batch.kubernetes.io/job-name=create-nextcloud-file && \
            echo "Here's the logs from the nextcloud pod:" && \
            kubectl logs -l app.kubernetes.io/name=nextcloud
